#!/usr/bin/env bash
set -euo pipefail

# ============================================================
# 一键环境修复脚本：zsh + oh-my-zsh + pcp + bashrc/zshrc 安全隔离
#
# 目标：
#   1. 新开终端自动进入 zsh
#   2. zsh 可以用原来 bashrc 里配置出来的命令，例如 ducc
#   3. 在 zsh 里执行 source ~/.bashrc 不会污染 prompt
#   4. 不再让 zsh 直接 source 完整 ~/.bashrc
#   5. 通用配置统一放到 ~/.shell_common
#
# 用法：
#   bash setup_env_final.sh
#   exec zsh
# ============================================================

# ---------- 0. 基础变量 ----------
BASHRC="$HOME/.bashrc"
ZSHRC="$HOME/.zshrc"
COMMON_RC="$HOME/.shell_common"

TS="$(date +%Y%m%d_%H%M%S)"

BASHRC_BACKUP="$HOME/.bashrc.backup_before_zsh_setup.$TS"
ZSHRC_BACKUP="$HOME/.zshrc.backup_before_zsh_setup.$TS"

LEGACY_BASHRC="$HOME/.bashrc.legacy_before_zsh_setup"
LEGACY_BASHRC_SANITIZED="$HOME/.bashrc.legacy_before_zsh_setup.sanitized"
LEGACY_ENV_RC="$HOME/.shell_common.from_old_bashrc_env"
LEGACY_ALIAS_RC="$HOME/.shell_common.from_old_bashrc_alias"

touch "$BASHRC"
touch "$ZSHRC"
touch "$COMMON_RC"

echo "==> 当前用户: $(whoami)"
echo "==> HOME: $HOME"

# ---------- 1. 代理设置：仅本次安装临时生效 ----------
# 代理凭据通过环境变量传入，勿硬编码在脚本里。
: "${http_proxy:?请先 export http_proxy=http://user:pass@host:port}"
: "${https_proxy:?请先 export https_proxy=http://user:pass@host:port}"
export HTTP_PROXY="$http_proxy"
export HTTPS_PROXY="$https_proxy"

export no_proxy="${no_proxy:-localhost,127.0.0.1}"
export NO_PROXY="$no_proxy"

echo "==> 使用代理: $http_proxy"

# ---------- 2. 备份当前配置 ----------
echo "==> 备份当前 .bashrc / .zshrc"

cp "$BASHRC" "$BASHRC_BACKUP"
cp "$ZSHRC" "$ZSHRC_BACKUP"

echo "    .bashrc 备份到: $BASHRC_BACKUP"
echo "    .zshrc  备份到: $ZSHRC_BACKUP"

# 这个 legacy 文件后续专门给 bash 使用，不给 zsh 直接 source
cp "$BASHRC_BACKUP" "$LEGACY_BASHRC"

# ---------- 3. 安装依赖 ----------
echo "==> 安装 zsh / git / curl / rsync / coreutils"

if command -v apt-get >/dev/null 2>&1; then
    PROXY_CONF="/etc/apt/apt.conf.d/99zsh-install-proxy"

    if [ -w /etc/apt/apt.conf.d ]; then
        {
            echo "Acquire::http::Proxy \"$http_proxy\";"
            echo "Acquire::https::Proxy \"$https_proxy\";"
        } > "$PROXY_CONF"

        cleanup_apt_proxy() {
            rm -f "$PROXY_CONF"
        }
        trap cleanup_apt_proxy EXIT
    else
        echo "    /etc/apt/apt.conf.d 不可写，跳过 apt 代理文件"
    fi

    apt-get update
    apt-get install -y zsh git curl rsync coreutils

elif command -v yum >/dev/null 2>&1; then
    yum install -y zsh git curl rsync coreutils

elif command -v dnf >/dev/null 2>&1; then
    dnf install -y zsh git curl rsync coreutils

else
    echo "未找到 apt-get / yum / dnf，请手动安装 zsh / git / curl / rsync / coreutils" >&2
    exit 1
fi

echo "==> zsh 版本:"
zsh --version

# ---------- 4. 安装 oh-my-zsh ----------
echo "==> 安装 oh-my-zsh"

export RUNZSH=no
export CHSH=no

if [ -d "$HOME/.oh-my-zsh" ]; then
    echo "    已存在 ~/.oh-my-zsh，跳过"
else
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" || {
        echo "    oh-my-zsh 安装失败，继续使用普通 zsh"
    }
fi

# ---------- 5. 设置 zsh 为默认 shell ----------
echo "==> 设置 zsh 为默认 shell"

ZSH_PATH="$(command -v zsh)"

if [ -w /etc/shells ]; then
    grep -qx "$ZSH_PATH" /etc/shells 2>/dev/null || echo "$ZSH_PATH" >> /etc/shells
else
    echo "    /etc/shells 不可写，跳过写入 $ZSH_PATH"
fi

chsh -s "$ZSH_PATH" "$(whoami)" 2>/dev/null || {
    echo "    chsh 修改失败，容器环境常见，后续用 .bashrc 自动 exec zsh"
}

# ---------- 6. 清理 legacy bashrc 里的旧脚本 block ----------
echo "==> 清理旧配置 block"

cp "$LEGACY_BASHRC" "$LEGACY_BASHRC_SANITIZED"

# 删除之前脚本写入过的 block，避免递归、重复、污染 prompt
sed -i \
    -e '/# >>> auto-exec-zsh (added by setup_env.sh) >>>/,/# <<< auto-exec-zsh (added by setup_env.sh) <<</d' \
    -e '/# >>> load-bashrc-in-zsh (added by setup_env.sh) >>>/,/# <<< load-bashrc-in-zsh (added by setup_env.sh) <<</d' \
    -e '/# >>> pcp function >>>/,/# <<< pcp function <<</d' \
    -e '/# >>> pcp function (added by setup_env.sh) >>>/,/# <<< pcp function (added by setup_env.sh) <<</d' \
    -e '/# >>> load-shell-common (added by setup_env.sh) >>>/,/# <<< load-shell-common (added by setup_env.sh) <<</d' \
    -e '/# >>> load-shell-common >>>/,/# <<< load-shell-common <<</d' \
    -e '/# >>> zsh-guard-for-bashrc >>>/,/# <<< zsh-guard-for-bashrc <<</d' \
    "$LEGACY_BASHRC_SANITIZED" 2>/dev/null || true

# ---------- 7. 从旧 bashrc 里提取环境变量，给 zsh 使用 ----------
echo "==> 从旧 .bashrc 提取 PATH / 环境变量"

cat > "$LEGACY_ENV_RC" <<'EOF'
# This file is generated by setup_env_final.sh.
# It imports useful env vars from the old ~/.bashrc.
EOF

# 用 bash 真实 source 一次旧 bashrc，然后把常见环境变量快照下来
# 这样 zsh 不需要直接 source bashrc，也可以拿到 ducc 等命令所在 PATH
LEGACY_BASHRC_SANITIZED="$LEGACY_BASHRC_SANITIZED" bash --noprofile --norc -i <<'BASHENV' >> "$LEGACY_ENV_RC" 2>/dev/null || true
source "$LEGACY_BASHRC_SANITIZED" >/dev/null 2>&1 || true

dump_var() {
    local name="$1"
    if [ "${!name+x}" = "x" ]; then
        printf 'export %s=%q\n' "$name" "${!name}"
    fi
}

dump_var PATH
dump_var LD_LIBRARY_PATH
dump_var PYTHONPATH
dump_var CPATH
dump_var LIBRARY_PATH
dump_var PKG_CONFIG_PATH
dump_var CUDA_HOME
dump_var CUDA_PATH
dump_var JAVA_HOME
dump_var GOPATH
dump_var GOROOT
dump_var http_proxy
dump_var https_proxy
dump_var no_proxy
dump_var HTTP_PROXY
dump_var HTTPS_PROXY
dump_var NO_PROXY
dump_var ONEAPI_AUTH_TOKEN
dump_var OPENAI_API_KEY

env | while IFS='=' read -r k v; do
    case "$k" in
        DUCC*|COMATE*|BAIDU*|PADDLE*|CUDA*|NCCL*|PYTHON*|LD_LIBRARY_PATH)
            printf 'export %s=%q\n' "$k" "$v"
            ;;
    esac
done
BASHENV

# 去重
awk '!seen[$0]++' "$LEGACY_ENV_RC" > "${LEGACY_ENV_RC}.tmp"
mv "${LEGACY_ENV_RC}.tmp" "$LEGACY_ENV_RC"

echo "    环境变量快照写入: $LEGACY_ENV_RC"

# ---------- 8. 从旧 bashrc 提取 alias ----------
echo "==> 从旧 .bashrc 提取 alias"

cat > "$LEGACY_ALIAS_RC" <<'EOF'
# This file is generated by setup_env_final.sh.
# It imports aliases from the old ~/.bashrc.
EOF

awk '
    /^[[:space:]]*alias[[:space:]][A-Za-z0-9_][A-Za-z0-9_]*=/ {
        print
    }
' "$LEGACY_BASHRC_SANITIZED" >> "$LEGACY_ALIAS_RC" || true

echo "    alias 快照写入: $LEGACY_ALIAS_RC"

# ---------- 9. 如果快照里仍然找不到 ducc，则主动搜索 ducc ----------
echo "==> 检查 ducc 是否可用"

if ! bash --noprofile --norc -c "source '$LEGACY_ENV_RC' >/dev/null 2>&1 || true; command -v ducc >/dev/null 2>&1"; then
    echo "    环境变量快照里没找到 ducc，开始搜索常见目录"

    DUCC_PATH="$(
        find /root /home /usr/local /opt /workspace /root/paddlejob \
            -type f -name ducc 2>/dev/null | head -1 || true
    )"

    if [ -n "$DUCC_PATH" ]; then
        DUCC_DIR="$(dirname "$DUCC_PATH")"
        echo "    找到 ducc: $DUCC_PATH"
        echo "export PATH=\"$DUCC_DIR:\$PATH\"" >> "$LEGACY_ENV_RC"
    else
        echo "    没有搜索到 ducc，可后续手动把 ducc 所在目录加入 ~/.shell_common"
    fi
else
    echo "    ducc 已可通过旧 .bashrc 的 PATH 找到"
fi

# ---------- 10. 写入 ~/.shell_common ----------
echo "==> 写入通用配置到 $COMMON_RC"

cat > "$COMMON_RC" <<'EOF'
# ============================================================
# ~/.shell_common
#
# bash / zsh 都会加载这个文件。
# 通用 PATH / alias / 函数都应该写在这里。
#
# 不要让 zsh 直接 source ~/.bashrc。
# ============================================================

# ---------- 从旧 bashrc 导入的环境变量 ----------
if [ -f "$HOME/.shell_common.from_old_bashrc_env" ]; then
    source "$HOME/.shell_common.from_old_bashrc_env"
fi

# ---------- 从旧 bashrc 导入的 alias ----------
if [ -f "$HOME/.shell_common.from_old_bashrc_alias" ]; then
    source "$HOME/.shell_common.from_old_bashrc_alias"
fi

# ---------- pcp 并行复制函数 ----------
pcp() {
    local src="${1:-}"
    local dst="${2:-}"
    local jobs="${3:-$(nproc)}"

    if [[ "$src" == "-h" || "$src" == "--help" ]]; then
        cat << HELP
并行复制工具，带基本进度信息。

用法:
  pcp <源目录> <目标目录> [并行数]

示例:
  pcp log backup
  pcp log backup 8
HELP
        return 0
    fi

    if [[ -z "$src" || -z "$dst" ]]; then
        echo "用法: pcp <源目录> <目标目录> [并行数]"
        return 1
    fi

    if [[ ! -d "$src" ]]; then
        echo "错误: 源目录 '$src' 不存在"
        return 1
    fi

    if ! [[ "$jobs" =~ ^[0-9]+$ ]] || [[ "$jobs" -lt 1 ]]; then
        echo "错误: 并行数必须是大于等于 1 的整数"
        return 1
    fi

    if ! command -v rsync >/dev/null 2>&1; then
        echo "错误: 未找到 rsync，请先安装 rsync"
        return 1
    fi

    if ! command -v realpath >/dev/null 2>&1; then
        echo "错误: 未找到 realpath，请先安装 coreutils"
        return 1
    fi

    mkdir -p "$dst"

    local abs_dst
    abs_dst="$(realpath "$dst")"

    echo "分析源目录..."

    local total_size
    local total_files
    local total_human

    total_size="$(du -sb "$src" | cut -f1)"
    total_files="$(find "$src" -type f | wc -l)"

    if command -v numfmt >/dev/null 2>&1; then
        total_human="$(numfmt --to=iec-i --suffix=B "$total_size")"
    else
        total_human="${total_size}B"
    fi

    echo "源目录: $src"
    echo "目标目录: $dst"
    echo "总大小: $total_human"
    echo "文件数: $total_files"
    echo "并行数: $jobs"
    echo

    (
        cd "$src" || {
            echo "错误: 无法进入源目录 $src"
            exit 1
        }

        find . -type d -print0 \
            | xargs -0 -r -P "$jobs" -I{} mkdir -p "$abs_dst/{}"

        find . \( -type f -o -type l \) -print0 \
            | xargs -0 -r -P "$jobs" -I{} rsync --relative -a {} "$abs_dst"
    )

    echo "复制完成！"
}
EOF

echo "    已写入 $COMMON_RC"

# ---------- 11. 重写 ~/.bashrc ----------
echo "==> 重写安全版 ~/.bashrc"

cat > "$BASHRC" <<'EOF'
# ============================================================
# ~/.bashrc
#
# 注意：
#   这个文件是 bash 专用入口。
#   如果你在 zsh 里误执行 source ~/.bashrc，只会加载 ~/.shell_common，
#   然后立即返回，不会污染 zsh prompt。
# ============================================================

# ---------- zsh 保护 ----------
# 如果当前 shell 是 zsh，说明用户误执行了 source ~/.bashrc。
# 此时只加载通用配置，然后 return，绝不继续加载 bash 专用配置。
if [ -n "${ZSH_VERSION:-}" ]; then
    if [ -f "$HOME/.shell_common" ]; then
        source "$HOME/.shell_common"
    fi

    return 0 2>/dev/null || exit 0
fi

# ---------- bash 加载通用配置 ----------
if [ -f "$HOME/.shell_common" ]; then
    source "$HOME/.shell_common"
fi

# ---------- bash 专用：加载旧 .bashrc ----------
# 旧 bashrc 只给 bash 使用，不给 zsh 使用。
if [ -f "$HOME/.bashrc.legacy_before_zsh_setup.sanitized" ]; then
    source "$HOME/.bashrc.legacy_before_zsh_setup.sanitized"
fi

# ---------- 交互式 bash 自动切换到 zsh ----------
# 容器里 chsh 经常不生效，所以这里兜底。
case $- in
    *i*)
        if [ -z "${ZSH_VERSION:-}" ] && command -v zsh >/dev/null 2>&1; then
            export SHELL="$(command -v zsh)"
            exec zsh
        fi
        ;;
esac
EOF

echo "    已写入 $BASHRC"

# ---------- 12. 重写 ~/.zshrc ----------
echo "==> 重写安全版 ~/.zshrc"

cat > "$ZSHRC" <<'EOF'
# ============================================================
# ~/.zshrc
#
# zsh 专用入口。
# 不要在这里 source ~/.bashrc。
# 通用配置统一 source ~/.shell_common。
# ============================================================

# ---------- oh-my-zsh ----------
if [ -d "$HOME/.oh-my-zsh" ]; then
    export ZSH="$HOME/.oh-my-zsh"
    ZSH_THEME="robbyrussell"
    plugins=(git)

    source "$ZSH/oh-my-zsh.sh"
else
    PROMPT='%F{green}%n@%m%f %F{blue}%1~%f %# '
fi

# ---------- 加载通用配置 ----------
if [ -f "$HOME/.shell_common" ]; then
    source "$HOME/.shell_common"
fi
EOF

echo "    已写入 $ZSHRC"

# ---------- 13. 最终验证 ----------
echo ""
echo "==> 验证 zsh 下命令可见性"

if zsh -ic 'source ~/.zshrc >/dev/null 2>&1; command -v pcp >/dev/null 2>&1'; then
    echo "    pcp: OK"
else
    echo "    pcp: 未检测到"
fi

if zsh -ic 'source ~/.zshrc >/dev/null 2>&1; command -v ducc >/dev/null 2>&1'; then
    echo "    ducc: OK"
else
    echo "    ducc: 仍未检测到。请手动把 ducc 所在目录加入 ~/.shell_common"
fi

echo ""
echo "============================================================"
echo "==> 全部完成"
echo ""
echo "下一步执行："
echo "  exec zsh"
echo ""
echo "验证："
echo "  source ~/.bashrc"
echo "  which ducc"
echo "  pcp -h"
echo ""
echo "如果 ducc 能找到但报 login 文件不存在，执行："
echo "  ducc login"
echo ""
echo "备份文件："
echo "  $BASHRC_BACKUP"
echo "  $ZSHRC_BACKUP"
echo ""
echo "通用配置以后写这里："
echo "  ~/.shell_common"
echo ""
echo "不要再手动把 source ~/.bashrc 写进 ~/.zshrc"
echo "============================================================"
